#ifndef DEFINES_H
#define DEFINES_H

#define HEADER_HEIGHT 50
#define BUTTON_SIZE 40
#define BUTTON_OFFSET_X 10
#define BUTTON_OFFSET_Y 5
#define DISPLAY_WIDTH 90
#define DISPLAY_OFFSET_X 20
#define DISPLAY_OFFSET_Y 5
#define COMBOBOX_WIDTH 290
#define COMBOBOX_HEIGHT 70
#define INFO_DIALOG_OFFSET 5
#define MENU_FONT_SIZE 20
#define START_BUTTON_OFFSET_Y 100


#endif